Processing data
Mahdi-Niazi/Blog-App pull request #2
Opened 2023-10-26 18:56 UTC by Mahdi-Niazi

### In this milestone I:

- Add user model
- Add post model
- Add like model
- Add comments model
- Add recent_post method
- Add update_post_counter
- Add recent_comments
- Add update_like_counter method
- Add update_comment_counter method

2023-10-26 19:49 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Mahdi-Niazi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Implemented some project requirements. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-26 19:49 UTC, Qoosim commented on app/models/post.rb
> +  end
- [ ] Great job for making use of one of the [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html), `after_save`. it is also good to make this method `private`. Kindly make it private

2023-10-26 19:49 UTC, Qoosim commented on app/models/comment.rb
> +  end
- [ ] Great job for making use of one of the [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html), `after_save`. it is also good to make this method `private`. Kindly make it private. It should look something similar to this :point_down: 

```
  class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comment_counter

  private
  def update_coumment_counter
    Post.find(post_id).update(comments_counter: Comment.where(post_id).count)
  end
```

2023-10-26 19:49 UTC, Qoosim commented on app/models/like.rb
> +  end
- [ ] Great job for making use of one of the [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html), `after_save`. it is also good to make this method `private`. Kindly make it private. It should look something similar to this :point_down: 

```
  class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_like_counter

private  
def update_like_counter
    Post.find(post_id).update(likes_counter: Like.where(post_id).count)
  end
```

2023-10-27 04:31 UTC, Shedrack-Sunday approved these changes
Hi @Mahdi-Niazi  👍 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails features  ✔️  
- [x] Kudus on meeting the requirements   👏 


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-27 04:32 UTC, merged