Validations
Mahdi-Niazi/Blog-App pull request #3
Opened 2023-10-27 05:10 UTC by Mahdi-Niazi

Add the following validations:
For the User model:
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
For the Post model:
Title must not be blank.
Title must not exceed 250 characters.
CommentsCounter must be an integer greater than or equal to zero.
LikesCounter must be an integer greater than or equal to zero.
Add unit specs for all of your models' methods and validations.

2023-10-27 05:27 UTC, Shedrack-Sunday requested changes
Hello @Mahdi-Niazi  👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with Rails model✔️
- Kudus creating a couple pf model validations      ✔️  

# - Required Changes  🌵  

- [ ] Kindly implement model validations for all  files as you did in  `user`  model test

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-27 05:27 UTC, Shedrack-Sunday commented on spec/post_spec.rb
> +  end
- [ ] Based on project requirements, you're expected to Add unit specs for all of your models' methods and validations.
- You did this in the `user` test, which i must commend you for 👏 . Kindly do same for the other three models.

#
## Sample as done in user model test:
```
describe 'validations' do
  it { should validate_presence_of(:name) }
end
```
### Requirement:
![image](https://github.com/Mahdi-Niazi/Blog-App/assets/50990925/683eaead-8d3f-46c4-a8d3-23bdfb4f2b86)

2023-10-28 10:52 UTC, Mahdi-Niazi commented
Dear Reviewer,

I am currently in terminal have a flight I have done this changes kindly approved and please ignore if it have any error cause I don't have time to correct. 


Thank you in advance!

2023-10-28 14:14 UTC, joel-kalema approved these changes
Hi @Mahdi-Niazi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights

Tests are passing 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-28 17:04 UTC, merged